language: ruby
rvm:
  - 2.5.1

cache: bundler

install: bundle install
script: jekyll build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "XhE2Eo31bRqFOwDMVjd96FXFklvHZeWfr4LU7hviBzeco/+UI00FKTdVDwT0k0CPObON9OCqGPVVKg9cgN8+AGUmshzKDIuzoi3PHTpUWKgoGxaSMfYxPavfvDHHmVs3pbxTEJTpMNNCt0t0s6yIu/qgFWByipo4pUMKnW6u9iJYq/esIHR8GXNDQWHbuERbDFcrMLEvXzq9/UXvKaqKE4H4z3nLSR8rJLND1mfOSCYpQqDSJTERwsWKS/zfqOfRyzaSP0ZuLK4xBwtZtmvN28LKrVYbJ963hZnS8WVY07sD50UxrSxMoqgTAvLnrGo25nIyjeQkZdzal51cL0th/537gT7nXJ84upxR0+jpiyG0FveLCWqO664hngsETrX4NmOBT4Hol8070GiqqVxi08KkvlgszgHMjc2XaSAM3bp6CLNmiX1nMjQCK6qdTvpsuE1Ky36tA/3an7ba0iSk+rMMbhc2/hg6Zdwjj0bFLuoqFNL1NFbwQjJb+lI73HSUygrgIO6PwHYP6NV4cxHvoPGO6ob9z97FK+ps5geer5GfUzr1+hSTsss4rkOSzXp1Z6LoU2rWpbl50F8R9qIMiigwSasLF/GuGQyHI2tYzLTBr79vmgIjMHEEdpN5j4z6zyu2rb8SctS95XumrX/MR5Gkft/2oBz3IGXqo59+Ybc="
  on:
    branch: master

env:
 - JEKYLL_ENV=production